---
version: '3'
services:
  jobmanager:
    build:
      context: ./images/flink/
      args:
        FLINK_VERSION: 1.13.0
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.13.0.jar

  taskmanager:
    build:
      context: ./images/flink/
      args:
        FLINK_VERSION: 1.13.0
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.13.0.jar
